apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: devops/config:v2.0
        imagePullPolicy: IfNotPresent
        env:
        - name: AUTHOR
          value: config-server
        - name: EUREKA_SERVER
          value: "http://eureka-0.eureka:8761/eureka/,http://eureka-1.eureka:8761/eureka/,http://eureka-2.eureka:8761/eureka/"
        ports:
        - containerPort: 12000
